# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9daba87a9f6ea7d85006df92f14352e74498c01fbd7b6187a28b038abb5113d2367635f88e754f6d72d8700719e0c53b16d8357f50287231063ea8912aa799ec

test:
  secret_key_base: 9a5ece7fe9074a6d98b907e016624f28ad8e1f4f1103c423265c6235264bb41ad4c839fd1b93cd4d69464c40a346d732335a022555ef0aa67dd631f9104c3004

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
